"""empty message

Revision ID: c68d4e05b9a8
Revises: d911dfe357a3
Create Date: 2024-01-08 11:34:39.606767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68d4e05b9a8'
down_revision = 'd911dfe357a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
